#index:
#    path: /
#    controller: App\Controller\DefaultController::index

fos_js_routing:
  resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

_liip_imagine:
  resource: "@LiipImagineBundle/Resources/config/routing.yaml"